{
 "title": "django-crud-observability",
 "description": "vizualization for django-crud-app metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "HTTP by status, method, endpoint",
   "type": "bargauge",
   "description": "Provides data about target of the request, method and status code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "django_http_responses_total_by_status_view_method_total",
     "legendFormat": "{{status}} - {{method}} - {{view}}"
    }
   ]
  },
  {
   "title": "CRUD status",
   "type": "bargauge",
   "description": "<POST> reuqests to app models",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "django_model_inserts_total", "legendFormat": "create - {{model}}" },
    { "expr": "django_model_updates_total", "legendFormat": "update - {{model}}" },
    { "expr": "django_model_deletes_total", "legendFormat": "delete - {{model}}" }
   ]
  },
  {
   "title": "RPS || Latency",
   "type": "graph",
   "description": "Requests per period of time and Latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "django_http_requests_body_total_bytes_sum",
     "legendFormat": "rps"
    },
    {
     "expr": "django_http_requests_latency_including_middlewares_seconds_sum",
     "legendFormat": "avg latency"
    }
   ]
  },
  {
   "title": "Detail Latency",
   "type": "gauge",
   "description": "Latency statistics grouped by view controller and http method",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_sum",
     "legendFormat": "{{view}} - {{method}}"
    }
   ]
  },
  {
   "title": "postgres stats",
   "type": "stat",
   "description": "postgres stats: executes, connections, queries per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "django_db_execute_total", "legendFormat": "executes" },
    {
     "expr": "django_db_new_connections_total",
     "legendFormat": "connections"
    },
    {
     "expr": "django_db_query_duration_seconds_sum",
     "legendFormat": "query avg duration"
    }
   ]
  }
 ]
}