version: "3.9"

services:

  postgres:
    image: postgres
    container_name: crud-postgres
    user: postgres
    volumes:
      - ./pg_data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  employee-app:
    image: karmawow/employee-app
    container_name: employee-app
    build: ./
    volumes:
      - .:/home/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
