version: "3.9"

volumes:
  app_data: {}

services:

  postgres:
    image: postgres
    container_name: crud-postgres
    user: postgres
    volumes:
      - ./pg_data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  employee-app:
    image: karmawow/employee-app
    container_name: employee-app
    build: ./
    volumes:
      - .:/home/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
  
  prometheus:
    image: prom/prometheus:v2.21.0
    volumes:
      - ./utils/prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090

  promtail:
    image: grafana/promtail:1.6.1
    volumes:
      - app_data:/var/log

  grafana:
    image: grafana/grafana:7.3.6
    ports:
      - 3000:3000
